### ISSUE TITLE
Undefined array key 1

### ISSUE THREAD

**Issue by mabdullahsari** [opcodesio/log-viewer#102]
Hello

I've seen this has been brought up before in #84 previously. We are using **v1.4.2** which should be the latest version.

You should be able to reproduce it using this dump and the latest Laravel release: https://pastebin.com/5QF5fB2V
This only happens when you toggle either of the checkboxes (Error / None).

**Comment by arukompas** [comment]
Hey @mabdullahsari 

Thanks a lot for the report! The Pastebin link helped **a lot**.

The fix is ready in the newest `v1.4.3` release. Hope this works!

**Comment by mabdullahsari** [comment]
> Hey @mabdullahsari
> 
> Thanks a lot for the report! The Pastebin link helped **a lot**.
> 
> The fix is ready in the newest `v1.4.3` release. Hope this works!

Thanks for the quick reply! I can confirm this is fixed **mostly**: an empty line at the start of the log file still makes it crash, but as soon as you remove that, it works again as usual.

That empty line in Line #1 was **not** added by me, but the logger.

**Comment by arukompas** [comment]
@mabdullahsari - does re-building the index for the log help? I still have the log file with an empty line at the beginning, and it does work for me just fine 🤔 

Are you on PHP 8.1 ?

**Comment by mabdullahsari** [comment]
Yeah, it did help. Sorry for wasting your time. 😬
I am on 8.1 yes, but it is all fine now.

Ty!

**Comment by arukompas** [comment]
No worries, happy to help! :D

**Comment by fh32000** [comment]
same error 

Undefined array key 1

https://flareapp.io/share/Bm0jjQD7#F65

@arukompas

**Comment by fh32000** [comment]
https://flareapp.io/share/VP666YwP#F67

**Comment by arukompas** [comment]
hey @fh32000 ,

can you provide me with:
- Laravel version
- PHP version
- Log Viewer version (exact, you can see it in bottom-right corner)
- Upload the log file that fails to load

Thanks!
