### ISSUE TITLE
No cookie found

### ISSUE THREAD

**Issue by yoeriboven** [opcodesio/log-viewer#107]
<img width="1440" alt="Schermafbeelding 2022-09-16 om 12 49 20" src="https://user-images.githubusercontent.com/4047804/190624080-345cd4ca-b3c8-4a8f-98ff-e71fa0f22664.png">

Just installed the package on a new app. Every time I reload the page above a new entry of the warning is added.

The current line:

```php
$this->preferences = json_decode($request->cookie(self::COOKIE_KEY), true) ?? [];
```

A possible fix:
```php
$this->preferences = json_decode($request->cookie(self::COOKIE_KEY) ?? '', true) ?? [];
```

This is on PHP 8.1.10

**Comment by arukompas** [comment]
hey @yoeriboven , thanks for the report!

A fix for this is ready in `v1.4.5` 😄
