### ISSUE TITLE
Undefined Array Key 1

### ISSUE THREAD

**Issue by michele-grifa** [opcodesio/log-viewer#110]
I read the #84 and #102 and i'm on version `1.4.5`, but parsing the logs raise the exception.

Exception: https://flareapp.io/share/xmN3KqpP#F59
Full Logs: https://pastebin.com/AHUrCin9

Laravel Version: 8.83.23
PHP Version: 8.0.1

**Comment by arukompas** [comment]
Hey @michele-grifa , do you have the ability to upgrade to a newer 8.0 patch version? 

PHP 8.0 is currently at `8.0.21` already.

PHP `8.0.21` and Laravel `8.83.23` work fine here, the log file provided opens up without issues.

<img width="1422" alt="Screenshot 2022-09-23 at 11 34 48" src="https://user-images.githubusercontent.com/8697942/191922185-5091358b-2591-415f-8489-136eddf51483.png">
<img width="1176" alt="Screenshot 2022-09-23 at 11 35 00" src="https://user-images.githubusercontent.com/8697942/191922201-ad917b7c-e617-46d7-bbd0-e0bc61be6351.png">

**Comment by michele-grifa** [comment]
Hey @arukompas i will try, i have to rebuild the docker image.

**Comment by arukompas** [comment]
Hey @michele-grifa - I have **just** managed to get my hands on a PHP 8.0.1 version on a Windows using XAMPP.

On a brand new Laravel installation, it works as expected:
    
<img width="1225" alt="Screenshot 2022-09-23 at 13 17 19" src="https://user-images.githubusercontent.com/8697942/191940611-38d6f239-753e-454c-ab8e-57bbdb8fdca0.png">
<img width="769" alt="Screenshot 2022-09-23 at 13 18 49" src="https://user-images.githubusercontent.com/8697942/191940638-009a6e80-7c09-46fb-9638-5e54ac4834ea.png">

----

Maybe you can share the Dockerfile (and docker-compose.yml if you're using that) so I can help figure out what's wrong with the setup? Thanks!

**Comment by michele-grifa** [comment]
I updated the docker image to 8.0.2 and the problem seems to be resolved. Thanks

**Comment by arukompas** [comment]
@michele-grifa That's interesting. Thanks for letting me know!
