### ISSUE TITLE
The log was empty

### ISSUE THREAD

**Issue by gakkiismywife** [opcodesio/log-viewer#112]
php version : 8.1
laravel verison:8.0

![image](https://user-images.githubusercontent.com/40749544/191700113-aa52faae-7d53-4771-b41e-8a09c20bf0dd.png)

**Comment by arukompas** [comment]
Hey @gakkiismywife 

Can you share the log file as well somewhere? Pastebin or just upload it here. It's usually something to do with the content of the file that might be messing up, or isn't handled properly. 

Thanks!

**Comment by gakkiismywife** [comment]
> Hey @gakkiismywife
> 
> Can you share the log file as well somewhere? Pastebin or just upload it here. It's usually something to do with the content of the file that might be messing up, or isn't handled properly.
> 
> Thanks!

{"time":"2022-09-24 11:18:15","payload":{"context":{"msg":"getTodayDiscuss","result":{"code":"100000","msg":"success","data":{"read":[{"time":"11:00","value":0},{"time":"12:00","value":0},{"time":"13:00","value":0},{"time":"14:00","value":0},{"time":"15:00","value":0},{"time":"16:00","value":0},{"time":"17:00","value":0},{"time":"18:00","value":0},{"time":"19:00","value":0},{"time":"20:00","value":0},{"time":"21:00","value":0},{"time":"22:00","value":0},{"time":"23:00","value":0},{"time":"00:00","value":0},{"time":"01:00","value":0},{"time":"02:00","value":0},{"time":"03:00","value":0},{"time":"04:00","value":0},{"time":"05:00","value":0},{"time":"06:00","value":0},{"time":"07:00","value":0},{"time":"08:00","value":0},{"time":"09:00","value":0},{"time":"10:00","value":0}],"me":[{"time":"11:00","value":0},{"time":"12:00","value":0},{"time":"13:00","value":0},{"time":"14:00","value":0},{"time":"15:00","value":0},{"time":"16:00","value":0},{"time":"17:00","value":0},{"time":"18:00","value":0},{"time":"19:00","value":0},{"time":"20:00","value":0},{"time":"21:00","value":0},{"time":"22:00","value":0},{"time":"23:00","value":0},{"time":"00:00","value":0},{"time":"01:00","value":0},{"time":"02:00","value":0},{"time":"03:00","value":0},{"time":"04:00","value":0},{"time":"05:00","value":0},{"time":"06:00","value":0},{"time":"07:00","value":0},{"time":"08:00","value":0},{"time":"09:00","value":0},{"time":"10:00","value":0}],"ori":[{"time":"11:00","value":0},{"time":"12:00","value":0},{"time":"13:00","value":0},{"time":"14:00","value":0},{"time":"15:00","value":0},{"time":"16:00","value":0},{"time":"17:00","value":0},{"time":"18:00","value":0},{"time":"19:00","value":0},{"time":"20:00","value":0},{"time":"21:00","value":0},{"time":"22:00","value":0},{"time":"23:00","value":0},{"time":"00:00","value":0},{"time":"01:00","value":0},{"time":"02:00","value":0},{"time":"03:00","value":0},{"time":"04:00","value":0},{"time":"05:00","value":0},{"time":"06:00","value":0},{"time":"07:00","value":0},{"time":"08:00","value":0},{"time":"09:00","value":0},{"time":"10:00","value":0}]}},"topic":"苹果超特斯拉成头号做空目标","monitor":{"id":151,"uuid":5252804807178616839,"name":"iPhone","start_time":"2022-09-22T16:00:00.000000Z","end_time":"2022-09-23T15:59:59.000000Z","employee_id":5247301272030445580,"organization_id":5247301272021794824,"config":{"type":2,"expression":"ios|iphone|iPhone|苹果|库克","except_expression":"16"},"created_at":"2022-09-15T06:48:21.000000Z","updated_at":"2022-09-23T02:29:50.000000Z","deleted_at":null}}},"application":"Laravel","server_addr":null,"remote_addr":"127.0.0.1","level":"INFO","target":"MonitorTopicProcess","api":"GET http://localhost","ip":"127.0.0.1","referer":null,"server_request_id":"-1","user_agent":"Symfony"}

**Comment by arukompas** [comment]
Hey @gakkiismywife 

This doesn't look like contents of a Laravel log file. It should start with a date time within square brackets, then the environment and severity level, like so:

```
[2022-09-22 12:34:56] local.ERROR ...
```
