### ISSUE TITLE
production.ERROR: Class "Opcodes\LogViewer\Utils\Utils" not found

### ISSUE THREAD

**Issue by Tiagospem** [opcodesio/log-viewer#126]
Hi, on production server sometimes this error occurs

`[2022-10-08 22:26:55] production.ERROR: Class "Opcodes\LogViewer\Utils\Utils" not found (View: /var/www/vhosts/topoleiloes.com.br/httpdocs/vendor/opcodesio/log-viewer/resources/views/livewire/log-list.blade.php) {"userId":20000,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): Class \"Opcodes\\LogViewer\\Utils\\Utils\" not found (View: /var/www/vhosts/topoleiloes.com.br/httpdocs/vendor/opcodesio/log-viewer/resources/views/livewire/log-list.blade.php)`

<img width="1423" alt="CleanShot 2022-10-08 at 22 34 29@2x" src="https://user-images.githubusercontent.com/8459781/194733431-786da98b-4820-4c8a-95aa-bd4028fc85d2.png">

**Comment by arukompas** [comment]
hey @Tiagospem , can you please try clearing the view cache? And updating to the latest Log Viewer. The class definitely exists.

**Comment by Tiagospem** [comment]
I don't know what happens anymore. I install the package via composer require, I run it the first time, it works perfectly, after a while, error 500 appears, always something is wrong, this only happens with a project in production.

``production.ERROR: Undefined variable $showLevelsDropdown (View: /var/www/vhosts/topoleiloes.com.br/httpdocs/vendor/opcodesio/log-viewer/resources/views/livewire/log-list.blade.php) (View: /var/www/vhosts/topoleiloes.com.br/httpdocs/vendor/opcodesio/log-viewer/resources/views/livewire/log-list.blade.php) {"userId":20000,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): Undefined variable $showLevelsDropdown (View: /var/www/vhosts/topoleiloes.com.br/httpdocs/vendor/opcodesio/log-viewer/resources/views/livewire/log-list.blade.php) (View: /var/www/vhosts/topoleiloes.com.br/httpdocs/vendor/opcodesio/log-viewer/resources/views/livewire/log-list.blade.php) at /var/www/vhosts/topoleiloes.com.br/httpdocs/storage/framework/views/1b6e4ae27ba0e61a057f2be9e60b9f03d350bd65.php:10)``

The only thing different is that I use the redis cache, but I have 7 other similar projects and that doesn't happen.

**Comment by arukompas** [comment]
Hey @Tiagospem 

The first video shows installation of a different package :) 
You can install this package with the command `composer require opcodesio/log-viewer`

Also the error `Undefined variable $showLevelsDropdown` is now different from the original one. I've released an update, `v1.6.3` which hopefully fixes this error for you :) Let me know!

**Comment by Tiagospem** [comment]
sorry, I confused the package installation :/, but the problem occurred with the correct package. Updated to the latest version, let's see, thanks

**Comment by arukompas** [comment]
No problem @Tiagospem 

Closing as it's potentially fixed. Let me know if there's still an issue with `v1.6.3` version.
