### ISSUE TITLE
Not loading Log Viewer, because of route /

### ISSUE THREAD

**Issue by dkvadratu** [opcodesio/log-viewer#131]
When I have route `Route::get('/', 'PagesController@home')->name('pages.home');` then `/log-viewer` doesn't work. Any ideas how to workaround this?

**Comment by arukompas** [comment]
@dkvadratu hey, what is the output of `php artisan route:list` ? You can remove sensitive any routes if you want.

Otherwise, I'd look into the `PagesController` class, especially the constructor to see if you're doing anything that would prevent other routes from being registered.

Also, check the `'route_path'` value in the `config/log-viewer.php` if you have published it.

**Comment by dkvadratu** [comment]
PagesController@home method just returns view blade with few variables. PagesController has no constructor.
 
I think in project that I got is something custom with routing in Kernel/Middleware, because if I remove first _GET / PagesController@home_, other custom links not working (log-viewer works). So for now its not an issue, I will update later.
 
 
 GET|HEAD   / ---------------- pages.home › PagesController@home  
  GET|HEAD   _debugbar/assets/javascript ---------------- debugbar.assets.js › Barryvdh\Debugbar › AssetController@js  
  GET|HEAD   _debugbar/assets/stylesheets ---------------- debugbar.assets.css › Barryvdh\Debugbar › AssetController@css  
  DELETE     _debugbar/cache/{key}/{tags?} ----------------. debugbar.cache.delete › Barryvdh\Debugbar › CacheController@delete  
  GET|HEAD   _debugbar/clockwork/{id} ---------------- debugbar.clockwork › Barryvdh\Debugbar › OpenHandlerController@clockwork  
  GET|HEAD   _debugbar/open ----------------. debugbar.openhandler › Barryvdh\Debugbar › OpenHandlerController@handle  
  GET|HEAD   api/user ----------------..  
  GET|HEAD   complaints ----------------...... pages.complaints › PagesController@complaints  
  POST       contact-us ----------------. contact.post › ContactUsController@post  
  GET|HEAD   cookies ----------------.... pages.cookies › PagesController@cookies  
  GET|HEAD   livewire/livewire.js ----------------.. Livewire\Controllers › LivewireJavaScriptAssets@source
  GET|HEAD   livewire/livewire.js.map ---------------- Livewire\Controllers › LivewireJavaScriptAssets@maps  
  POST       livewire/message/{name} ---------------- livewire.message › Livewire\Controllers › HttpConnectionHandler  
  GET|HEAD   livewire/preview-file/{filename} ---------------- livewire.preview-file › Livewire\Controllers › FilePreviewHandler@handle  
  POST       livewire/upload-file ----------------...... livewire.upload-file › Livewire\Controllers › FileUploadHandler@handle  
  GET|HEAD   log-viewer ----------------.... blv.index › Opcodes\LogViewer › IndexController  
  GET|HEAD   log-viewer/file/{fileIdentifier}/download ----------------. blv.download-file › Opcodes\LogViewer › DownloadFileController  
  GET|HEAD   log-viewer/folder/{folderIdentifier}/download ---------------- blv.download-folder › Opcodes\LogViewer › DownloadFolderController  
  GET|HEAD   log-viewer/is-scan-required ----------------.. blv.is-scan-required › Opcodes\LogViewer › IsScanRequiredController  
  GET|HEAD   log-viewer/scan-files ----------------......... blv.scan-files › Opcodes\LogViewer › ScanFilesController  
  GET|HEAD   log-viewer/search-progress ----------------. blv.search-more › Opcodes\LogViewer › SearchProgressController  
  POST       ****/**** ----------------..... ****Controller@****  
  POST       ****/**** ----------------......... ****Controller@****  
  POST       ****/****-**** ----------------....... ****Controller@****  
  POST       ****/****-****-**** ----------------........... ****Controller@****
  GET|HEAD   ****/****/{****_id} ---------------- ****Controller@continue  
  GET|HEAD   ****/****-pdf ----------------....... ****Controller@****  
  POST       ****/**** ----------------..... ****Controller@****  
  GET|HEAD   ****/****-pdf ----------------..... ****Controller@****  
  GET|HEAD   ****/****-pdf ---------------- ****Controller@****  
  POST       ****/**** ----------------. ****Controller@store  
  POST       ****/**** ---------------- ****ValidationController@store  
  GET|HEAD   ****.callback ---------------- ****.callback › ****Controller@callback  
  GET|HEAD   ****.failed ----------------...... ****.failed › ****Controller@failed  
  GET|HEAD   privacy-policy ---------------- pages.privacy › PagesController@privacy  
  GET|HEAD   **** ---------------- pages.**** › PagesController@****  
  GET|HEAD   ****-**** ---------------- pages.**** › PagesController@****  
  POST       ****/submit/{****} ---------------- ****Controller@***Submit
  GET|HEAD   translations ---------------- TranslationsController

**Comment by arukompas** [comment]
Hm, the list of routes does contain both the Log Viewer and your `PagesController@home` route.

And what do you mean by "does not work" ? Does it return 404? Or some other error?

**Comment by dkvadratu** [comment]
Sorry for unclear situation. 

Not working - route `/log-viewer` loads home page, `home.blade.php (PagesController@home)`

![image](https://user-images.githubusercontent.com/7911433/195503896-a5b2b9b6-ed9e-439c-bfe3-61b11ba96be0.png)

**Comment by arukompas** [comment]
That's so weird! I really want to help you, but I can't replicate the problem myself.

It really feels like the PagesController is catching all routes somehow.
- Do you get a successful response even to a non-Log Viewer route? Such as `/log-viewer-route-that-doesnt-exist` or just `/asdf`
- Do you have anything specific/special in your `RouteServiceProvider` or `AppServiceProvider` ?

**Comment by dkvadratu** [comment]
Sorry for disturbing. I think it was Cache or Composer problems. Reinstalled project in local environment and all routes works fine.

p.s. thanks for great tool!
