### ISSUE TITLE
Truncate long log names

### ISSUE THREAD

**Issue by ligne13** [opcodesio/log-viewer#140]
Hi,

Long names do not display nicely.

<img width="368" alt="image" src="https://user-images.githubusercontent.com/81624/197148543-5b1d12a5-4c73-4eb4-9112-5eb754633fcf.png">

**Comment by arukompas** [comment]
Hey @ligne13 , thanks for the report!

Should be fixed in `v1.6.4`. Not truncating, but instead wrapping the names, because some parts of the name can be important.
