### ISSUE TITLE
File-List Dropdown gets overlapped when there are multiple folders

### ISSUE THREAD

**Issue by m-thalmann** [opcodesio/log-viewer#141]
When there are multiple folders selected in the config, the dropdown gets overlapped by the folder-item (see image).

![grafik](https://user-images.githubusercontent.com/30590624/197547800-668349b4-228e-43fc-9a4e-72cc9af2086f.png)

The folder was including by adding the following to the `include_files`-config: `users/*.log`.

**Comment by arukompas** [comment]
Hey @m-thalmann , thanks for the report! 

Should be fixed in `v1.6.4` :)

**Comment by m-thalmann** [comment]
@arukompas thank you!
