### ISSUE TITLE
Bad folder-path displayed when using subfolders

### ISSUE THREAD

**Issue by m-thalmann** [opcodesio/log-viewer#142]
When including a subfolder by adding `users/*.log` (for example) to the `include_files`-config, the folder-item displays the full path as title for the directory, which I don't think is the correct behaviour. Also this is not the full-path, since it only points to the root of the Laravel-Application. The log-files are still displayed correctly though.

![grafik](https://user-images.githubusercontent.com/30590624/197549122-082665d3-5457-48e0-99cc-77b27ead1359.png)

Correct path in this case would be: `C:\Users\matthias.thalmann\Work\splus-dashboard-new-re\api\storage\logs\users`

Edit: The sub-folder is not included automatically, if that should be the case. Therefore I had to add it manually.

**Comment by arukompas** [comment]
Hey @m-thalmann , thanks for the report!

Should be fixed in `v1.6.4` :)

**Comment by m-thalmann** [comment]
@arukompas thanks! Great work!
