### ISSUE TITLE
"No results" even though the file contains entries

### ISSUE THREAD

**Issue by mgjgid** [opcodesio/log-viewer#150]
Hello

First of all: great work with this package, i love it and added it to all my laravel projects.

I'm facing a odd behaviour as you can see in the screenshot below:
The horizon.log is 1.05MB and also contains data if i look at the file in a raw editor, but the log-viewer shows "no results"

<img width="997" alt="image" src="https://user-images.githubusercontent.com/36155814/201041713-ed107caf-b9f9-4516-a525-aa3fec9939a4.png">

(Browser cache cleared, Cookies & Local storage cleared, log-viewer index rebuilt, permissions of log file checked)

Is there any way i can dive deeper into the reading process and see what's happening (or not happening).
Thanks.

**Comment by arukompas** [comment]
Hey @mgjgid - unfortunately quite recently Horizon changed their log format, which is not supported by the Log Viewer yet.

See the issue #108 for more infor.

Thanks for reporting! But closing as duplicate :)
