### ISSUE TITLE
sometime can't open a Log file. Getting a error "Undefined array key 1"

### ISSUE THREAD

**Issue by meet-7span** [opcodesio/log-viewer#156]
production.ERROR: Undefined array key 1 {"exception":"[object] (ErrorException(code: 0): Undefined array key 1 at /vendor/opcodesio/log-viewer/src/Log.php:50)

![image](https://user-images.githubusercontent.com/101455648/201923738-1bb5b8d9-d8c0-4d5c-b0a4-f01d65b58986.png)

**Comment by arukompas** [comment]
Hey @meet-7span , what version of the Log Viewer do you have installed? Can you please update to the latest version (`v1.6.5`) which may have fixed the issue already? Thanks! :)

**Comment by arukompas** [comment]
Hey @meet-7span , any news? Have you had time to test out the newest release?

**Comment by meet-7span** [comment]
Yeah when i update the version it's work for me. 
Thanks buddy :)
