### ISSUE TITLE
Livewire encountered corrupt data when trying to hydrate the component.

### ISSUE THREAD

**Issue by aryala7** [opcodesio/log-viewer#166]
hey guys, i've encountered this error when i added this package to my project.
i have followed your instructions and publish all the required configs. but when i want to open a file in my logs list, this page comes up.
is there way to fix it?
![image](https://user-images.githubusercontent.com/56627259/204805092-f5326ed3-eaf1-4b44-96de-e19c53a6c9c3.png)

**Comment by aryala7** [comment]
hey @arukompas thanks for the reply.
no i didn't disable any middleware and this is my **web middleware group** in _Kernel.php
```
'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \App\Http\Middleware\SetDefaultGuard::class,
        ],
        ```

**Comment by jynxy** [comment]
+1 on this issue

**Comment by arukompas** [comment]
Hey @jynxy , can you also share your middlewares configured in the Kernel.php file, as well as your `config/log-viewer.php` contents? Thanks!

**Comment by jynxy** [comment]
`        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],`

there is no config/log-viewer.php ?

**Comment by jynxy** [comment]
any news on fixing this @arukompas

**Comment by arukompas** [comment]
Hey @jynxy , sorry but I won't have any free time this week. I'll take a stab on it next week most likely.

Have you tried fixing it yourself? Any idea what could be broken?

Do you maybe have an example repository you can share where this error happens? This way I could try and replicate it easier.

**Comment by arukompas** [comment]
Hey all, I've just released v2 of the Log Viewer without the Livewire dependency. It should now work a lot better and in more environments.

Read more about the v2 release and how to upgrade here - https://arunas.dev/log-viewer-v2/

Closing this for now. If you still have issues with v2, please open a new issue. Thanks! 😀
