### ISSUE TITLE
Count and Data mismatched.

### ISSUE THREAD

**Issue by meet-7span** [opcodesio/log-viewer#168]
I found one issue in a log file. 

you can see my screenshot. There is 2 count displayed in the dropdown, but in the list, there is only one record displayed.
![image](https://user-images.githubusercontent.com/101455648/206108658-e9391737-3799-4da9-b483-3325cb83ebb6.png)

in the original log file, there are 2 records.

**Comment by arukompas** [comment]
Stale, most likely fixed. Closing.
