### ISSUE TITLE
Invalid hexadecimal escape sequence

### ISSUE THREAD

**Issue by dev-mo-ali** [opcodesio/log-viewer#172]
Uncaught SyntaxError: Invalid hexadecimal escape sequence
    at new AsyncFunction (<anonymous>)
    at log-viewer?file=404ac811-laravel.log:1522:4916
    at log-viewer?file=404ac811-laravel.log:1522:5074
    at log-viewer?file=404ac811-laravel.log:1522:5093
    at W (log-viewer?file=404ac811-laravel.log:1522:5386)
    at D (log-viewer?file=404ac811-laravel.log:1522:4494)
    at log-viewer?file=404ac811-laravel.log:1522:37902
    at Function.<anonymous> (log-viewer?file=404ac811-laravel.log:1522:14707)
    at n (log-viewer?file=404ac811-laravel.log:1522:8828)
    at log-viewer?file=404ac811-laravel.log:1522:8855

**Comment by arukompas** [comment]
Hey @dev-mo-ali , can you please share the full log file that you tried to read?

Or were trying to search it with some regex?

Please describe the context/scenario of when and how this happened, more in-depth.

Thanks!

**Comment by arukompas** [comment]
no response, perhaps fixed after all. Closing

**Comment by dev-mo-ali** [comment]
sorry for the late reply, yes fixed
