### ISSUE TITLE
Undefined variable $selectedFileIdentifier

### ISSUE THREAD

**Issue by Zlimon** [opcodesio/log-viewer#177]
Upgraded from v1.2.10 to v1.7.2 and get the following error:

`Undefined variable $selectedFileIdentifier`

I am using Laravel v9.45.1 with Inertia v0.11.1

**Comment by arukompas** [comment]
Hi @Zlimon , is it possible to get the full stack trace?

Thanks!

**Comment by arukompas** [comment]
Hey all, I've just released v2 of the Log Viewer without the Livewire dependency. It should now work a lot better and in more environments.

Read more about the v2 release and how to upgrade here - https://arunas.dev/log-viewer-v2/

Closing this for now. If you still have issues with v2, please open a new issue. Thanks! 😀
