### ISSUE TITLE
Allowed memory size error caused by the package 

### ISSUE THREAD

**Issue by centerdevs** [opcodesio/log-viewer#178]
Hi. I just added the package to my project and it looks really awesome. Thanks for the such a good tool 🔥

I have only one problem, when I open log viewer, it triggers an error. PHP memory_limit is 128MB, and chunk size in config is set to 50MB.

![IMG_20230104_005457](https://user-images.githubusercontent.com/45295727/210455284-031c3bce-3328-4a6b-945b-24a11bfc342a.jpg)

How can we deal with this?

**Comment by arukompas** [comment]
Hey @centerdevs , thanks for the kind words!

1. How big are your log files? Is it possible to get a screenshot of the file list on the left?
2. It's hard to tell when exactly this memory exception occurs. Can you explain a bit what actions are you taking before this exception occurs? Does it happen when first opening up the log viewer? Does it happen when navigating to a big file? Does it happen when searching? etc etc. Exact steps, so I can reproduce it.

Thanks!

**Comment by centerdevs** [comment]
1. I have logs/laravel.log that is always lightweight ( up to 1mb ). And i have larger logs files stored in subfolders, ex. logs/*/big.log - some of big are 150-200mb in size, and my total log folder size is 8 GB.

2. When i open log-viewer, by default no one file selected, and the error almost instantly occurs by itself, like i see it - it indexing the whole log folder and because of total logs/* size there some problem. What is important, when i open any of "big" 100-200MB logs file - it's absolutelly fine i can explore them without any problem, this happening just with "background" indexing proccess.

3. BTW, an error occurrs 3-4 times ( 1 error per one log-viewer page refresh in browser ) and after it stops to occurring. It feels like indexing proccess was finished and it will be repated after some time, it's not triggered anymore. After 5 min when i open log-viewer - the error is already triggered :)

**Comment by centerdevs** [comment]
I've temporary commented out the code in the the following files - IsScanRequiredController, ScanFilesController.

So now i'll have no errors triggered by the files scanner and the most important - i'll have no scanning of 8GB logs, that i don't really need to scan. It's "cold" logs with some important historical information.

**Comment by arukompas** [comment]
Hey @centerdevs , thanks for helping debug the issue!

I've tagged a new release, `v1.8.0` which allows you to disable this eager scanning done at the beginning. I understand not everyone needs this, so this setting makes perfect sense.

Just added some info about it in the docs as well - https://log-viewer.opcodes.io/docs/configuration/managing-indices

Let me know if resolves the issue!

**Comment by centerdevs** [comment]
Updated and it works awesome now! thanks a lot !
