### ISSUE TITLE
Unable to view log files

### ISSUE THREAD

**Issue by zstarpak** [opcodesio/log-viewer#184]
Hi,
I have log files shown in the sidebar, however when i click on them, there is a 404 window opening with errors on the browser console window.
Following are the screenshots:
Logs Visible:
![image](https://user-images.githubusercontent.com/9010666/212440545-da844b24-9bd6-4e73-a03f-af9471903c00.png)

404 upon clicking:
![image](https://user-images.githubusercontent.com/9010666/212440584-d561533f-7c6e-4637-bcd8-11c2dd9c744d.png)

**Comment by arukompas** [comment]
Hey @zstarpak how are you running the Laravel project?

Artisan serve, Valet, Sail, Docker, Vagrant, Xampp, Laragon, or something else?

It sounds like there's an issue with the server setup.

**Comment by ekibimo** [comment]
same here, i got this error
![image](https://user-images.githubusercontent.com/10369594/212856595-9b0966ce-d516-4cfb-8e83-d968d4d3ac1a.png)
using laravel 9 and xampp running in local dev

**Comment by zstarpak** [comment]
Hi @arukompas I am running it through my Wamp server, directly in the root laravel folder with modified `.htaccess` so the `index.php` is inside the `root/main` folder instead of `public` folder

**Comment by arukompas** [comment]
@zstarpak do other routes in your `web.php` file work as expected? Or is the log viewer the only thing on the app so far?

It seems to me that there's a misconfiguration.

Can you share your modified `.htaccess` and your `web.php` routes file? Thanks!

**Comment by zstarpak** [comment]
Yes @arukompas all other routes in `web.php` and `api.php` work fine as well as laravel's own auth routes.

Here is the `.htaccess` file. It is placed in the root folder same as where `index.php` is instead of `public` folder in root folder.

```.htaccess
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews -Indexes
    </IfModule>

    RewriteEngine On

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

    # Send Requests To Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>

```

Here is my `web.php`:

```php
<?php
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\StudentRequestController;

Auth::routes();
Route::get('/', [HomeController::class, 'login']);

Route::get('public/privacy-policy', function () {
    $settings = getSettings('privacy_policy');
    echo $settings['privacy_policy'];
});

Route::get('cron/complete-requests', [StudentRequestController::class, 'cronCompleteRequests']);

```

**Comment by iagofrota** [comment]
I'm having this same problem.

**Comment by yogeshGroony** [comment]
Same Issue

**Comment by arukompas** [comment]
Hey all, I've just released v2 of the Log Viewer without the Livewire dependency. It should now work a lot better and in more environments.

Read more about the v2 release and how to upgrade here - https://arunas.dev/log-viewer-v2/

Closing this for now. If you still have issues with v2, please open a new issue. Thanks! 😀
