### ISSUE TITLE
Can't select log file on mobile

### ISSUE THREAD

**Issue by bendix-dev** [opcodesio/log-viewer#185]
On mobile devices (definitely reproducible with the iPhone 12 Pro simulator in the Chrome Dev Tools) you can't select a log file so you can't view your logs at all except through search.

![127 0 0 1_8000_logs(iPhone 12 Pro)](https://user-images.githubusercontent.com/49339747/213215466-2be18990-379e-47e0-b60b-e238e2b59f9e.png)

**Comment by arukompas** [comment]
Hey @bendix-dev , the log viewer is currently not mobile friendly. That's planned for v2 later this year.
