### ISSUE TITLE
Undefined variable $selectedFileIdentifier

### ISSUE THREAD

**Issue by Nabajyoti4** [opcodesio/log-viewer#187]
[Error-Log.pdf](https://github.com/opcodesio/log-viewer/files/10506770/Error-Log.pdf)

**Comment by arukompas** [comment]
Hey all, I've just released v2 of the Log Viewer without the Livewire dependency. It should now work a lot better and in more environments.

Read more about the v2 release and how to upgrade here - https://arunas.dev/log-viewer-v2/

Closing this for now. If you still have issues with v2, please open a new issue. Thanks! 😀
