### ISSUE TITLE
Octane cache driver does not support cache keys

### ISSUE THREAD

**Issue by LarsCaspers** [opcodesio/log-viewer#191]
First off, thanks for this useful package!

An error occurs when selecting a log file. This happens only when i use Octane as the cache driver.
It looks like the cache keys log-viewer uses are too long. Is there any way to fix this?

![Screenshot 2023-02-14 at 15 38 36](https://user-images.githubusercontent.com/44041509/218769702-addc930e-6287-44f8-99f0-7c620992b54c.png)

**Comment by arukompas** [comment]
That's interesting... I haven't tested it with the Octane cache driver. I'm currently rewriting the Frontend to Vue and a few other changes. I'll make sure to shorten the cache keys as well. Keep an eye out for a release, possibly next week :)

**Comment by arukompas** [comment]
Hey @LarsCaspers ,

I've done some testing with Octane and unfortunately I wasn't able to make it work. Even with shorter keys (which are limited to 63 chars, btw), there are further limitations to the **content** of the cache which just doesn't work with Log Viewer at the moment.

Your best bet would be to use a different cache driver for Log Viewer - `file`, `redis`, `array` (in-memory, non-persistent), etc.

You can change the Log Viewer cache driver with an `.env` variable:
```env
LOG_VIEWER_CACHE_DRIVER=file
```

Hope this helps!

**Comment by LarsCaspers** [comment]
Hey Arunas,

Thanks a lot for taking the time! Shame octane cache isn't a good fit for log-viewer. Luckily the workaround fixes the issue.

Thanks again,

Lars Caspers
________________________________
Van: Arunas Skirius ***@***.***>
Verzonden: maandag, februari 20, 2023 8:08 AM
Aan: opcodesio/log-viewer ***@***.***>
CC: LarsCaspers ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [opcodesio/log-viewer] Octane cache driver does not support cache keys (Issue #191)


Hey @LarsCaspers<https://github.com/LarsCaspers> ,

I've done some testing with Octane and unfortunately I wasn't able to make it work. Even with shorter keys (which are limited to 63 chars, btw), there are further limitations to the content of the cache which just doesn't work with Log Viewer at the moment.

Your best bet would be to use a different cache driver for Log Viewer - file, redis, array (in-memory, non-persistent), etc.

You can change the Log Viewer cache driver with an .env variable:

LOG_VIEWER_CACHE_DRIVER=file

Hope this helps!
