### ISSUE TITLE
[2.0] First folder expanded by default

### ISSUE THREAD

**Issue by GC-Mark** [opcodesio/log-viewer#199]
Not sure if this was a conscious design decision, but since upgrading to `v2` the first folder on the left hand side is now open by default, which i am finding a little annoying as that folder is the one i need to access the least, so I always have to close it upon first visit.

Thanks 👍

**Comment by arukompas** [comment]
Hey @GC-Mark yes, there was a small change in logic unconsciously due to refactor, thanks for letting me know! :) 

The previous logic was to open the `root` folder automatically, not the first folder. So I've reverted back to that logic in `v2.0.2` now.

Hope this helps! :)

**Comment by GC-Mark** [comment]
Brilliant, thank you 👍
