### ISSUE TITLE
"app.js failed to load" - Issues

### ISSUE THREAD

**Issue by benbelmour** [opcodesio/log-viewer#211]
Currently, this package works fine locally as can be seen here:

![image](https://user-images.githubusercontent.com/79989595/224053635-a50c04c9-6a34-47ef-b463-2b0cb26b44e6.png)

But upon deploying to a server and attempting to view the log files via {app-url}/log-viewer, this error arises:

![image](https://user-images.githubusercontent.com/79989595/224053809-d766cabc-a3d4-48ee-8d0a-07a8806efdc3.png)

This is an error in console:

Mixed Content: The page at '{url}/log-viewer' was loaded over HTTPS, but requested an insecure stylesheet '{url}/vendor/log-viewer/app.css?id=2d577fa607de6eeef7cfb84d3b72b864'. This request has been blocked; the content must be served over HTTPS.

I have attempted various things from within the server:

- php artisan vendor:publish --tag=log-viewer-assets --force
- php artisan log-viewer:publish

But the error still remains, any help would greatly be appreciated!

**Comment by arukompas** [comment]
Hey, what's the value of `APP_URL` in your `.env` file?

I feel like it's simple HTTP, but should be HTTPS

**Comment by LHongy** [comment]
Hello, I have the same issue, but I have my APP_URL using https already.

**Comment by LHongy** [comment]
I added code in AppServiceProvider boot() method, As reference from this post: https://stackoverflow.com/questions/34378122/load-blade-assets-with-https-in-laravel
```
if(config('app.env') === 'production') {
        \URL::forceScheme('https');
 }
```

This solved the issue, but not sure if it is a fine solution.

**Comment by arukompas** [comment]
Hey @benbelmour @LHongy 

Laravel automatically guesses the scheme from the incoming request, but if your app is behind a proxy, Docker container, or some other indirect configuration, it might not get it correctly.

For this to work, you then need to define the asset URL manually in your `.env`

```env
ASSET_URL=https://example.com
```

Hope this helps!

**Comment by cAstraea** [comment]
In the past adding the ASSET_URL used to fix it but seems it has returned now :( with app.css being the culprit app.css failed to load. Please refresh the page, re-publish Log Viewer assets, or fix routing for vendor assets.

**Comment by GhadaKhamisM** [comment]
@arukompas I have the same issue 
This from console
log-viewer:14 Mixed Content: The page at 'https://base_url/log-viewer' was loaded over HTTPS, but requested an insecure stylesheet 'http://base_url/vendor/log-viewer/app.css?id=12c5e78a91987c11d8a0cc04436541e9'. This request has been blocked; the content must be served over HTTPS.
log-viewer:1 Mixed Content: The page at 'https://base_url/log-viewer' was loaded over HTTPS, but requested an insecure script 'http://base_url/vendor/log-viewer/app.js?id=10fd202d284550adc56be1499fbd44c1'. This request has been blocked; the content must be served over HTTPS.

**Comment by Jexraiden** [comment]
I am having the same problem. I have a client that is using a load balancer, and the log-viewer page shows the error: app.css failed to load. Please refresh the page, re-publish Log Viewer assets, or fix routing for vendor assets.

We've already added APP_URL and ASSET_URL to the .env file

Also when looking to the assets in the networks tab, the assets that are loading correctly in other pages are pointing correctly like this: /{site}/build/assets/app.css.

But inside the log-viewer page it is pointing like this: /{site}/vendor/log-viewer/app.css?id={numbers}. The correct path would be something like vendor/log-viewer/public/app.css ?

I've ommited some date putting it inside brackets.

**Comment by xYvanB** [comment]
Same problem here, trying to show the log on a local env. 
Already modified APP_URL and added ASSET_URL with the same data but still get 
![image](https://github.com/user-attachments/assets/e2dba319-4e1f-40f8-9c27-aab49b5de553)

I have tried both http and https but I keep getting the same error
![image](https://github.com/user-attachments/assets/73aa8af1-6776-4a11-aa95-aa466ba77245)

The commands I executed are: 
- `composer require opcodesio/log-viewer`
- `php artisan log-viewer:publish`
- `php artisan vendor:publish --tag="log-viewer-config"`

**Comment by arukompas** [comment]
@xYvanB what does your application's `public` folder look like? Does it have a `vendor` folder and within it a `log-viewer` folder with JS and CSS files?

```
public
└ vendor
    └ log-viewer
        └ app.js
        └ app.css
```

If you have that, the next step is to make sure your http server actually serves all content from the `public` folder. For that I don't have any instructions since there's so many ways to run a PHP application behind http, but that's just an idea of what you could check.
