### ISSUE TITLE
Regular error

### ISSUE THREAD

**Issue by gakkiismywife** [opcodesio/log-viewer#22]
php version : 8.1
laravel version:8

When I visit the log-viewer path ,it went wrong.

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/40749544/186588697-33a7cdbe-8a9d-42fc-9533-2c9dc4c4dfd0.png">

**Comment by arukompas** [comment]
hey @gakkiismywife , can you please share the log file you tried to open? Please upload the whole file here.

Thanks!

**Comment by arukompas** [comment]
Hey @gakkiismywife - I have just experienced the same error myself and it had to do with very large log entries (mine was 70 MB)

I have fixed the error in the release https://github.com/opcodesio/log-viewer/releases/tag/v1.1.2 , so please upgrade the log viewer package with `composer update opcodesio/log-viewer` 😄 

Closing the issue, but let me know if it's still happening after upgrade!

**Comment by muarachmann** [comment]
Hi @arukompas I don't have this with large files, I am experiencing this with my horizon.log file. See below. And it's pointing to the same error
<img width="326" alt="Screen Shot 2022-08-29 at 15 48 24" src="https://user-images.githubusercontent.com/16350814/187229343-3bec7e0b-d1ac-4739-9e74-4b86ef4bc809.png">

<img width="328" alt="Screen Shot 2022-08-29 at 15 49 00" src="https://user-images.githubusercontent.com/16350814/187229560-ca372693-54c0-4f01-83bf-f5a60aeaf3f8.png">

**Comment by arukompas** [comment]
hey @muarachmann , this isn't exactly a horizon log that we support.

Horizon logs look something like this:
```
[2022-07-19 22:32:17][ca590ba4-d9d9-4a01-8989-f546a76f2381] Processing: App\User\UserActions\CreateNewUserAction
[2022-07-19 22:32:17][ca590ba4-d9d9-4a01-8989-f546a76f2381] Processed:  App\User\UserActions\CreateNewUserAction
[2022-07-19 22:32:17][9494e763-cd53-4fd5-885b-3b841a100621] Processing: App\User\UserActions\CreateNewUserAction
[2022-07-19 22:32:17][9494e763-cd53-4fd5-885b-3b841a100621] Processed:  App\User\UserActions\CreateNewUserAction
```

They have a timestamp, the job's ID, the state (processing, processed, failed, etc), and the job class that's being processed.

Yours look completely different! Might want to look again at how [supervisor is configured](https://laravel.com/docs/9.x/horizon#supervisor-configuration)

Hope this helps!

**Comment by muarachmann** [comment]
> supervisor is configured

Hi @arukompas this is true but when ever I start horizon "usually when my machine restarts", it runs `artisan horizon` which logs this `Horizon started successfully`. This is a new application and I haven't ran any jobs yet. When I run jobs I have the logs you have above. Also I noticed the `$matches[]` is responsible for this error since it's awaiting the format you put up above.

**Comment by arukompas** [comment]
@muarachmann ahh yes, I can see that in my own horizon logs this `Horizon started successfully.` string exists as well!

I'll push a fix for this later today. Thanks for letting me know!! 👍

**Comment by arukompas** [comment]
@muarachmann hey! Just pushed a new release, `v1.2.2` - https://github.com/opcodesio/log-viewer/releases/tag/v1.2.2

Please upgrade and it should fix the issue for you 😄 

Thanks for reporting the bug!
