### ISSUE TITLE
e.folders.flatMap is not a function

### ISSUE THREAD

**Issue by arukompas** [opcodesio/log-viewer#224]
### Discussed in https://github.com/opcodesio/log-viewer/discussions/223

<div type='discussions-op-text'>

<sup>Originally posted by **asad6ek** April  3, 2023</sup>
what could be the reason for this?
![image](https://user-images.githubusercontent.com/53338664/229492820-69703588-62f1-4d48-8f30-324b46ffb668.png)
</div>

**Comment by arukompas** [comment]
Fixed in `v2.4.1`

**Comment by xavi7th** [comment]
Good day.

I am still experiencing this problem on the latest update

**Comment by urameshibr** [comment]
@xavi7th Please, translate to english and you will can understand.

GPT says:

O erro "flatMap não existe" geralmente ocorre quando o método flatMap não é suportado pelo navegador ou pelo ambiente em que o código JavaScript está sendo executado. Isso acontece porque flatMap é uma função introduzida no ECMAScript 2019 (ES10) e, portanto, pode não estar disponível em versões mais antigas de navegadores ou ambientes JavaScript.

Para resolver esse problema, você pode substituir o uso de flatMap por um código equivalente usando map e flat (ou flatMap em browsers mais modernos). A função flat é introduzida no ECMAScript 2021 (ES12).

Aqui está como você pode reescrever a linha de código usando map e flat:
```javascript

// Antes
files: (state) => state.folders.flatMap((folder) => folder.files),

// Depois (usando map e flat)
files: (state) => state.folders.map((folder) => folder.files).flat(),


``` 
Essa modificação irá converter a matriz de arquivos de cada pasta em uma matriz de matrizes e, em seguida, nivelá-la em uma única matriz, que é essencialmente o que flatMap faz.

No entanto, se você estiver usando um ambiente JavaScript moderno que suporta flatMap (como navegadores mais recentes ou Node.js em versões recentes), você pode continuar usando flatMap normalmente, já que é uma função muito útil para manipulação de matrizes. Se você estiver usando ferramentas como o Babel para transpilar seu código JavaScript, também pode configurá-lo para transformar o flatMap em código compatível com versões mais antigas do ECMAScript.
