### ISSUE TITLE
Logs in subfolders not showing up

### ISSUE THREAD

**Issue by VitruxPT** [opcodesio/log-viewer#247]
Hi,

I've been trying to use this package but I can't seem to figure out how to display all files inside subfolders.
(I'm using the latest version of this package - V2.5.1)

I have these folders, all of them with laravel logs inside
![image](https://github.com/opcodesio/log-viewer/assets/20666039/a4ef5158-7a2b-4eea-aee4-a1d233ad01cb)

However, when I open log viewer, only these 2 files show up
<img width="391" alt="image" src="https://github.com/opcodesio/log-viewer/assets/20666039/d34d6c48-a60e-4f62-8328-a73488f07b51">

This is my log-viewer.php config file on the include and exclude keys.
From what I read in the documentation, I shouldn't need to change it since it's already looking at all `*.log` files in the "storage" folder so I can't see what's wrong.
![image](https://github.com/opcodesio/log-viewer/assets/20666039/34f67ed2-c3ad-4701-a15a-a3d72992e7f0)

Thank you in advance for your help.

**Comment by arukompas** [comment]
Hm, I just realised that `**` (a.k.a. "globstar") is not supported in PHP. Will have to figure out a different way to include recursive subdirectories.

In the meantime, you can manually configure each folder , or at least the number of levels available, like so:

```php
    'include_files' => [
        '*.log',
        '*/*.log',
        '*/*/*.log',
        '*/*/*/*.log',
        // and so on...
    ],
```

**Comment by arukompas** [comment]
nevermind :D 

Hey @VitruxPT , can you try the latest release, **v2.5.2**, it should contain a solution for recursive folders.

Hope this helps!

**Comment by VitruxPT** [comment]
It works now, thank you so much @arukompas!

<img width="381" alt="image" src="https://github.com/opcodesio/log-viewer/assets/20666039/4a817553-dd76-482a-bda5-ad7686d41e17">

I would suggest a different ui/ux to display the folder structure a little better like expanding each folder/subfolder instead of showing all subfolders folders separately but that's just a ui/ux suggestion!

Thank you so much for the fix again :)
