### ISSUE TITLE
Error Backtrace is shown in one line

### ISSUE THREAD

**Issue by tonyjoe-dev** [opcodesio/log-viewer#252]
Version installed: **v2.5.3**

Error Backtrace is shown in one line and then it's not easy to read:

![Backtrace](https://github.com/opcodesio/log-viewer/assets/139711237/0d074336-ec70-40f1-ac93-5772dae42be8)

**Comment by arukompas** [comment]
hey @tonyjoe-dev , this should now be fixed in **v2.5.4** :) I've used front-end processing instead, leaving the API intact.
