### ISSUE TITLE
It strips out JSON fragments from a message

### ISSUE THREAD

**Issue by lezhnev74** [opcodesio/log-viewer#254]
I just found out that the current version (2.5.2) strips out chunks of the message's body.

For example, a message contains this snippet:
```
...
Headers: {
    "x-goog-api-client": "gl-php\/8.2.8 gccl\/19.2.0 gapic\/19.2.0 gax\/1.19.1 grpc\/1.56.0 rest\/1.19.1 pb\/3.23.4+c",
    ...
}
Request: 
...
```

But in the log-viewer we see this:
```
...
Headers: 
Request: 
...
```

Could you advice how to configure log-viewer to show the full bodies of messages?

**Comment by arukompas** [comment]
hey @lezhnev74 , I've tagged a new version **v2.5.4** which now includes ability to leave JSON objects intact within the log.

Go to `config/log-viewer.php` and add this at the end:

```php
    'strip_extracted_context' => false,
```

it will still extract context, but it won't remove it from the rest of the log.

Hope this helps! :)

**Comment by lezhnev74** [comment]
Wow, thank you @arukompas ! We are giving this a shot and I'll be back next week :pray:
