### ISSUE TITLE
[Feature] Is it possible to support schedule scheduling log ???

### ISSUE THREAD

**Issue by shuqingzai** [opcodesio/log-viewer#267]
At present, it seems that there is no support for schedule log display, and it is hidden? Is there something wrong with the way I use it? Still not supported? ?

log-viewer is not displayed, but there is this log file in my log directory

![image](https://github.com/opcodesio/log-viewer/assets/44406033/1a65adc0-d261-4565-85d6-3cf91ca6b994)

![image](https://github.com/opcodesio/log-viewer/assets/44406033/541d95d4-5d5c-4dfd-8ed9-0f281c232c93)

The log content is roughly as follows, laravel schedules log output

```log
  2023-08-23 01:25:03 Running ['artisan' horizon:snapshot] ...... 1,208ms DONE
  ⇂ '/usr/local/bin/php' 'artisan' horizon:snapshot > '/dev/null' 2>&1  


   INFO  No scheduled commands are ready to run.  


   INFO  No scheduled commands are ready to run.  


   INFO  No scheduled commands are ready to run.  


  2023-08-23 01:29:02 Running ['artisan' horizon:snapshot] ........ 553ms DONE
  ⇂ '/usr/local/bin/php' 'artisan' horizon:snapshot > '/dev/null' 2>&1  

```

**Comment by arukompas** [comment]
hey @shuqingzai , it's not supported at the moment :) 

Please see ["Custom Log Types"](https://log-viewer.opcodes.io/docs/3.x/log-types/custom) on how to create additional log parsers for Log Viewer.

Unfortunately I won't have much time until next year to write any additional parsers myself, so I'll close this issue for now.
