### ISSUE TITLE
Checkboxes on severity dropdown are not visible on safari. 

### ISSUE THREAD

**Issue by davidsalazar** [opcodesio/log-viewer#272]
Screenshot below. 

![CleanShot 2023-09-01 at 11 19 43@2x](https://github.com/opcodesio/log-viewer/assets/14309/6fc91c5e-d636-4740-823a-12dc8976e388)

**Comment by arukompas** [comment]
hey @davidsalazar , thanks for the report! 

It's now fixed in the latest version - **v3.1.2**
