### ISSUE TITLE
Class "Opcodes\LogViewer\Level" not found when upgrading from v2 to v3.

### ISSUE THREAD

**Issue by sefakor20** [opcodesio/log-viewer#276]
I encountered an issue when attempting to upgrade from version 2 to version 3 in my Laravel project. The problem is that the package throws an error related to the class "Opcodes\LogViewer\Level" which is not found after the upgrade.

![Screenshot from 2023-09-19 22-23-44](https://github.com/opcodesio/log-viewer/assets/36778454/99a4a4fa-2407-408a-ad42-d06334ddf744)

### Environment
- PHP Version: 8.2
- Laravel Version: 10.x
- Operating System: Linux (Ubuntu)

I have followed the upgrade instructions provided by the package documentation

Please is there a way to resolve this issue?

**Comment by arukompas** [comment]
hey @sefakor20 , please see the [upgrade guide](https://log-viewer.opcodes.io/docs/3.x/upgrade#changes-to-configlog-viewerphp) and remove the unused `'patterns'` option from your `config/log-viewer.php`.

With that, also remove any `Opcodes\LogViewer\Level` namespace imports as that is no longer used.

Hope this helps! :)

**Comment by sefakor20** [comment]
Greetings @arukompas,

Thank you so much for your help in resolving this issue! I appreciate your quick response and effort to fix the problem. 

The upgrade to v3 of the package is now working perfectly in my project.
