### ISSUE TITLE
 JsonResource::withoutWrapping() used in controllers changes all other resources I have in my project (as I use Octane)

### ISSUE THREAD

**Issue by ofaws** [opcodesio/log-viewer#278]
![image](https://github.com/opcodesio/log-viewer/assets/91540029/2b6bb535-4d9c-4fcf-9de0-0e9d2a86d078)

Please make the package compatible with Laravel Octane

**Comment by arukompas** [comment]
hey @ofaws , thanks for the report!

This is now fixed in the latest version, **v3.1.3** :)
