### ISSUE TITLE
Newlines to <br> lost in context ouput

### ISSUE THREAD

**Issue by GavG** [opcodesio/log-viewer#284]
The prepareContextForOutput method translates newlines to <br> tage for display.

https://github.com/opcodesio/log-viewer/blob/main/resources/js/components/BaseLogTable.vue#L193

However, the output is then passed through the highlightSearchResult method:

https://github.com/opcodesio/log-viewer/blob/main/resources/js/helpers.js#L16

Which calls escapeHtml, escaping any added \<br\> tags.

I suspect an additional,:

```
.replace(/&lt;br\/&gt;/g, '<br/>');
```

Call might solve the issue, I can't forsee this opening up an XSS vector.

**Comment by GavG** [comment]
Addressing in the above PR: https://github.com/opcodesio/log-viewer/pull/285

**Comment by arukompas** [comment]
Thanks a lot for the report and the fix @GavG 💪
