### ISSUE TITLE
Custom theme not working as advertised

### ISSUE THREAD

**Issue by promanapeople** [opcodesio/log-viewer#319]
```
//config/log-viewer.php
/* -----------------------------------------------------------------
     |  Theme
     | -----------------------------------------------------------------
     |  Make your own theme by adding a folder to the views directory and specifying it here.
     */

    'theme'         => 'log-viewer',
```
Results in 
`local.ERROR: View [log-viewer.dashboard] not found.`

As shown the files appear to be in the right(?) place:
![Screenshot 2024-01-26 102000](https://github.com/opcodesio/log-viewer/assets/83995152/e574c766-d5a3-411f-8002-4836f8b7e3e3)

**Comment by arukompas** [comment]
Hey @promanapeople 

Log Viewer does not have a configurable team. Where did you find it?

**Comment by promanapeople** [comment]
Our mistake! It looks like there's been another log viewer package installed. Thanks for your time.
