### ISSUE TITLE
Problem downloading logfiles from log viewer page

### ISSUE THREAD

**Issue by francislivinglegend** [opcodesio/log-viewer#321]
Hi,

I'm having issues when attempting to download the logs from the log viewer page. If I try to do it on localhost it all works fine, but if I try to do it on the production website I get an error saying that the file was not found in the server.

![image](https://github.com/opcodesio/log-viewer/assets/134559680/1e1ee60f-26c9-428f-a75b-b82f59c5453c)

**Comment by arukompas** [comment]
hey @francislivinglegend , can you please share the request from the browser's Network tab, including request and response headers?

If there's multiple requests when you click the "Download" button, then share them all.

Thanks!
