### ISSUE TITLE
Search is case sensitive for non English text

### ISSUE THREAD

**Issue by decadence** [opcodesio/log-viewer#336]
Hello. Thanks for the package. I noticed that search is case sensitive when you search non English words.

No results for "ошибка"
![2024-02-25_16-36-52](https://github.com/opcodesio/log-viewer/assets/1434668/14f0cb1a-5a16-4567-b7f4-7c1050cc8cc8)

Results for "Ошибка"
![2024-02-25_16-36-34](https://github.com/opcodesio/log-viewer/assets/1434668/7286893e-85f7-479c-a356-34ff41042985)

English word matched even in different register
![2024-02-25_16-36-08](https://github.com/opcodesio/log-viewer/assets/1434668/bf15568e-57bd-4d57-bb9f-3c9e4de68ec6)

**Comment by arukompas** [comment]
hey @decadence thanks for the report and very clear instructions/examples 😄 

I've tagged a new release [**v3.5.0**](https://github.com/opcodesio/log-viewer/releases/tag/v3.5.0) which should fix the issue. Let me know if it doesn't work.

**Comment by decadence** [comment]
Thanks! Will give this a try.
