### ISSUE TITLE
Blank Display

### ISSUE THREAD

**Issue by masterei** [opcodesio/log-viewer#340]
![Screenshot_2024-02-29_14-49-35](https://github.com/opcodesio/log-viewer/assets/34229270/a68695f9-0e92-43c4-ab1d-350357ee0ceb)

**Laravel version:** 8.12
**Issue:** Blank display, no error in the console whatsoever.

**Comment by arukompas** [comment]
hey @masterei , can you share the **response headers** for both the `app.js` and `app.css` file requests?

If they are `text/plain` or `text/html` then the assets are not served correctly by your Apache/nginx server.

**Comment by masterei** [comment]
hey @arukompas, finally I found the culprit. It was the response caused by middleware of tidy package something which I already disabled; after that log viewer was working fine.

Btw, thank you for the support and for this great package of yours.
