### ISSUE TITLE
Arrays with numeric keys are not correctly displayed

### ISSUE THREAD

**Issue by jarno-hh** [opcodesio/log-viewer#347]
I have this message in my log file

`[2024-03-13 12:57:30] local.DEBUG: This is a log message {"array":{"10":"value1","20":"value2"}}`

In the log viewer this message is displayed like

![Screenshot 2024-03-13 at 14 08 03](https://github.com/opcodesio/log-viewer/assets/132431102/41bbab23-6ebb-4a2a-ae41-53cc77570cfa)

As you can see the numeric keys are gone in the log viewer.

**Comment by arukompas** [comment]
hey @jarno-hh , thanks for the bug report and the clear instructions :) Was easy to reproduce and it is now fixed in the latest versions of both v2 (v2.6.0) and v3 (v3.6.0) of Log Viewer.
