### ISSUE TITLE
Request failed with status code 500: Undefined array key 1 error when searching

### ISSUE THREAD

**Issue by lparede** [opcodesio/log-viewer#349]
Hello.

When searching in a certain log file for a specific term, sometimes I get the following messages: Request failed with status code 500: Undefined array key 1

Using the browser inspector, I can see that the problem is in the following file:
![image](https://github.com/opcodesio/log-viewer/assets/28596833/40c25f81-2bb3-4160-aecb-26541a040cc1)

It seems that in somes cases, index 1 of array variable $matches is not defined. If I make a eval of $matches[1], then the errors occurs in $matches[7].

![image](https://github.com/opcodesio/log-viewer/assets/28596833/d760e68c-9c70-4afd-97f1-dfc210715aee)

Anyone with the same problem? Can I make pull request to solve this?

**Comment by arukompas** [comment]
Hey!

Match at index 1 should be the date time. Is there a reason why a log entry does not have a datetime?

Perhaps you can share the log file (in full) with which I can reproduce the bug? Just seems weird 🤔

**Comment by lparede** [comment]
Yes, it's very weird. All the log entries have timestamp.

Unfortunately, I cannot share the log file, but you gave me a hint of debug.

Please hold the pull request that I made.

**Comment by lparede** [comment]
So, after another debug, I noticed that the log file has records without timestamps.

This is a custom log file. I will have to find out why this problems occurs.

`"""
NFO: http  {"inputs":{"_token":"KAbDqtFJIkKrgADXSwAZu1Ru7uoNc9uBgXJVzO1X","classId":"B","periodId":"3_2","spEditionId":"206","disciplineId":"535","startDate":"2
 ▶

ns%5B0%5D%5Bname%5D=id&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%
 ▶
"""`

`"""
[2024-03-15 16:13:43] production.INFO: http  {"inputs":[],"url":"/pt/myesenfc/study","ip":"193.137.66.240","http_method":"GET","server":"my.esenfc.pt","referrer
 ▶

s%5B1%5D%5Borderable%5D=false&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=classes&columns%5B2%5D
 ▶

"""`

**Comment by arukompas** [comment]
Hey @lparede 

Check what the surrounding content is inside the log file itself, not just what the log viewer shows. 

It could be that one of the logs contains something that looks similar to a log structure and Log Viewer thinks it's a new entry.

That's why sharing even an excerpt of the log file can be helpful in debugging.

**Comment by lparede** [comment]
Problem solved!

Somehow the custom log file got some corrupted data. I used a third party package to log the user activity, but I made my own middleware to do that and now the log files are ok.
