### ISSUE TITLE
Result not showing (Redis connection error)

### ISSUE THREAD

**Issue by FaisalKhokherWaada** [opcodesio/log-viewer#356]
I am getting a bug when viewing a log route GUI, however, if I have a successful connection with the Redis client Redis is working fine, but I don't know why this error is occurring.

Request failed with status code 500: `SELECT` failed: ERR SELECT is not allowed in cluster mode

Error 👎 
![Screenshot 2024-04-03 174303](https://github.com/opcodesio/log-viewer/assets/108063295/b4048be3-90b3-4175-82f9-263ee6735714)

**Comment by arukompas** [comment]
@FaisalKhokherWaada I assume you got it fixed? Make sure Redis is accessible through Laravel itself, so maybe try some Redis operations via the Laravel Artisan Tinker, or some test web route.
