### ISSUE TITLE
Error "Route [log-viewer.index] not defined" after activation flag LOG_VIEWER_API_ONLY = true

### ISSUE THREAD

**Issue by batteryf1** [opcodesio/log-viewer#365]
Hello!
Route "log-viewer.index" is used for the web part of extension.
I can find this name by path "routes/web.php"

So, If I enable LOG_VIEWER_API_ONLY, Laravel can't find route name "log-viewer.index" and returns a 500 error

**Comment by arukompas** [comment]
hey @batteryf1 , that's a great point!

Update made in **v3.8.1**, which makes sure the `log-viewer.index` route is always available. But, if the `log-viewer.api_only` config is set to true, the route will simply return HTTP 404.

https://github.com/opcodesio/log-viewer/releases/tag/v3.8.1
