### ISSUE TITLE
Cannot publish config `php artisan log-viewer:publish --tag=config`

### ISSUE THREAD

**Issue by khanakia** [opcodesio/log-viewer#368]
I tried below commands but no config file i see created in my config directory

```sh
php artisan log-viewer:publish
php artisan log-viewer:publish  --tag=config
```

**Comment by arukompas** [comment]
@khanakia hey,

the correct command is:

```shell
php artisan vendor:publish --tag=log-viewer-config
```

The `log-viewer:publish` only publishes the frontend assets, which is useful when updating the package to a newer version with newer assets.
