### ISSUE TITLE
Sidebar not showing

### ISSUE THREAD

**Issue by Autonoma-Bauernfeind** [opcodesio/log-viewer#399]
Hi everyone, 

I installed the package and I am also able to search for Logs, but the sidebar is not visible. It shows up for few ms and then disappears. 

We are using PHP 8.2.5 with an Laravel 9.52.16 installation 
<img width="1724" alt="Bildschirmfoto 2024-10-30 um 15 03 21" src="https://github.com/user-attachments/assets/ba101d87-956d-4c50-bdb0-4dccd0357986">

No console errors are shown

Is this a known bug?

Thanks!

**Comment by arukompas** [comment]
@Autonoma-Bauernfeind hey! Are there any notable network requests? Any 4xx or 5xx responses via the network tab? Share as much as you can :)

**Comment by Autonoma-Bauernfeind** [comment]
Thanks for the fast reply! Unfortunately not, everything looks fine to be honest.

<img width="1529" alt="Bildschirmfoto 2024-10-30 um 19 22 26" src="https://github.com/user-attachments/assets/246d5237-1c3d-415f-9fa7-704cf1b53c6d">

Not even a single console log message is showing.
The sidebar is flashing for a short time, and instantly hidden afterwards. 

Currently "opcodesio/log-viewer" with version "^3.11" is installed

https://github.com/user-attachments/assets/307d82be-5ece-4b74-a19f-b0221245a18d

**Comment by arukompas** [comment]
@Autonoma-Bauernfeind thank you!

Please share the following:
1. Console output, but please refresh the page after opening the console
2. Response from the `folders` XHR request, just to see whether the structure is correct.

**Comment by Autonoma-Bauernfeind** [comment]
Oh no, I found the error! A middleware is injecting an _events element into the response... 

I think this will cause the frontend to parse it as object instead of an array and can't iterate it properly....
<img width="788" alt="Bildschirmfoto 2024-11-01 um 01 31 44" src="https://github.com/user-attachments/assets/7dd6e51d-115d-449c-a629-20ac15ff67a7">

Thanks for helping me out and getting me on the right track! :) 

Best, Florian

**Comment by arukompas** [comment]
@Autonoma-Bauernfeind That's it, glad you found it! 🍻
