### ISSUE TITLE
log-viewer is producing warnings when triming null values

### ISSUE THREAD

**Issue by AComasSamcla** [opcodesio/log-viewer#400]
in src/Logs/Log.php, line 114:
```php
$this->message = trim($matches[static::$regexMessageKey] ?? null);
``` 
This produces a lot of warnings in laravel.log when there is no $matches[static::$regexMessageKey], because function trim expects a string.
There should be a previous condition to trim the message only when it is not null.

**Comment by arukompas** [comment]
hey @AComasSamcla , thanks for the report! Fixed in **v3.12.0** :)
