### ISSUE TITLE
Documentation - Broken link on default log types page

### ISSUE THREAD

**Issue by MrYamous** [opcodesio/log-viewer#409]
Hi

It's not directly related to the package, but I had no idea where else to report it.

There is a broken link to Custom Log Types on [Defaut Log Types](https://log-viewer.opcodes.io/docs/3.x/log-types/default#extending-a-pre-built-log-type) page between two code examples on the bottom of the page
![Capture d’écran 2024-12-18 082749](https://github.com/user-attachments/assets/9f760179-e1bd-452b-a2b4-ede0ac537c57)

Link point to ` .../log-types/custom-log-types` but good one looks like to be `.../log-types/custom`

**Comment by arukompas** [comment]
@MrYamous thanks for the report! That is now fixed 😄
