### ISSUE TITLE
No logs streamed

### ISSUE THREAD

**Issue by Norgul** [opcodesio/log-viewer#46]
Hello,

I tried using the package and it loads log files just fine (I can even download them with full content), however I am not getting anything in the view.

I am using non-published conf (all defaults), latest version (1.2.4) with L9.13.0.
Also tried `chmod -R 777 storage`, didn't help. Also tried flushing cache.

I am running a Docker container with Roadrunner server.

![image](https://user-images.githubusercontent.com/11718157/187907361-9f10bb22-130e-42f2-8c5b-3e831a5e1d3f.png)

**Comment by arukompas** [comment]
Hey @Norgul , I'm having trouble reproducing this.

I've set up a brand new Laravel project (v9.13.0 like yours), set up Roadrunner, and it works perfectly fine (both in Sail (docker) and native MacOS)

<img width="1727" alt="Screenshot 2022-09-01 at 19 41 48" src="https://user-images.githubusercontent.com/8697942/187967844-17800fc2-3aa0-4f59-a56f-ee082ea55ff2.png">

I do have a few questions that may help me figure out the issue.

1. Are you using a specific Livewire version yourself?

2. Have you modified the default `'web'` middleware group from Laravel? Make sure that cookies and send and a session is started, which is required for Livewire to function properly.

3. Does this happen to all the logs, or just this one file? Does it have a non-standard log format perhaps? Maybe you can paste the log file contents here.

4. Lastly, is there any other package or Octane/Roadrunner configuration that's non-standard and you believe you could interfere with this?

Thanks!

**Comment by Norgul** [comment]
Hey @arukompas, thanks for 

1. We are using Laravel for API only, and it started back in the 7.x version so it has no Livewire as a dependency. 
2. `web` middleware is intact
3. It happens to all the logs, and now that you mention it, yes, log format is slightly different:
> [2022-08-30 06:16:39.598814] [Process manager] 127.0.0.1 [] testing.INFO: Process type
4. That's a negative

Third point might be the real culprit here. Is there a way to configure that?

**Comment by arukompas** [comment]
@Norgul that's it. It's the custom log format.

Here's an example of the Regex we use to determine when it's the start of a new log entry - regexr.com/6t56r

You can see that your example does not get picked up.

Unfortunately, at the moment there's no way to configure the Regex used, BUT I do have plans to introduce "log reader drivers" which can be writte for pretty much any type of log in the future (laravel, mysql, apache, redis, etc).

So for now, if you really want to use this log viewer then I suggest forking the project for your own use and adjusting the Regex expressions found here:
- https://github.com/opcodesio/log-viewer/blob/main/src/LogReader.php#L12 - to determine the **start** of the log entry, including the timestamp and log severity (debug/info/error/etc) when indexing the file
- https://github.com/opcodesio/log-viewer/blob/main/src/Log.php#L11-L13 - to find the timestamp, severity from the full log entry

Closing this for now as it's not something I can fix right now, but let me know if there's anything else I can help with.

**Comment by arukompas** [comment]
@Norgul I may have figured something out... 🤔

**Comment by arukompas** [comment]
hey @Norgul !

I've just tagged a new release, `v1.2.5` which has a slightly different Regex that's more forgiving to custom log formats. Although your custom data (like ` [Process manager] 127.0.0.1 []`) is not in their own columns, it's still clearly visible and accessible!

<img width="1227" alt="Screenshot 2022-09-01 at 20 33 56" src="https://user-images.githubusercontent.com/8697942/187978583-63445e9e-b6b8-46bb-ada3-aae9bca36b4e.png">

Hope this helps 😄 

As for your PR, I'll review this tomorrow

**Comment by arukompas** [comment]
marking as fixed, let me know if there's still any issues.

**Comment by Norgul** [comment]
Yup, it works, thanks!
