### ISSUE TITLE
Hi, i have problem with the same files name

### ISSUE THREAD

**Issue by Virgo-SSS** [opcodesio/log-viewer#55]
Hi, i have problem with the same file name
*you can see at the picture,
i have same file name but with different directory folder, when i try to open A/test.log i can see the logs but when i try to open B/test.log it can't open the logs it keep going open the A/test.log.
how to solve this ?

![log-viewer](https://user-images.githubusercontent.com/85036198/188072827-e624f03f-007e-4ce4-8a1a-2a9bba23fcdc.png)

**Comment by arukompas** [comment]
@Virgo-SSS hey!

This is now fixed in the latest release, `v1.2.6`
