### ISSUE TITLE
Undefined variable $selectedFileName

### ISSUE THREAD

**Issue by Virgo-SSS** [opcodesio/log-viewer#63]
Hi after update the package, i got error Undefined variable $selectedFileName

![undefined variable](https://user-images.githubusercontent.com/85036198/188173807-d94b635f-1dc5-4db3-9e56-d9228ce6f014.png)

**Comment by arukompas** [comment]
Hey @Virgo-SSS ,

Can you please clear the view cache?

`php artisan view:clear`

**Comment by Virgo-SSS** [comment]
it's working fine, thank you
can close the issue

**Comment by arukompas** [comment]
Glad it helped :)
