### ISSUE TITLE
Error: Method Collection::linkCollection does not exist

### ISSUE THREAD

**Issue by rudiedirkx** [opcodesio/log-viewer#70]
I'm getting an error after opening a log file (in the popup/overlay):

> Method Illuminate\Support\Collection::linkCollection does not exist. (View: .../vendor/opcodesio/log-viewer/resources/views/pagination.blade.php) (View: .../vendor/opcodesio/log-viewer/resources/views/pagination.blade.php)

That's this line in the view:

    $links = $paginator->linkCollection()->toArray();

My Laraval version is `8.33.1`. Maybe `linkCollection` is newer? That should be in the requirements. Or maybe my custom setup is breaking something.

My `Illuminate\Pagination\LengthAwarePaginator` does have a method `linkCollection`, but it's protected.

**Comment by rudiedirkx** [comment]
If I change `protected function linkCollection` to `public` everything works perfectly, but eeeeeeh naaah. Did `linkCollection` change in some newer Laravel version or something?

**Comment by arukompas** [comment]
@rudiedirkx - you're right! It was made public only in Laravel 8.37.0

Pushing a fix soon.

**Comment by arukompas** [comment]
@rudiedirkx fixed in the new release, `v1.2.8`
