### ISSUE TITLE
hey @dkmonaghan , ok, so there's 2 bugs now! :D

### ISSUE THREAD

**Issue by Ashcjs** [opcodesio/log-viewer#73]
hey @dkmonaghan , ok, so there's 2 bugs now! :D 

### 1. The exception when viewing test.log
I'm still finding it difficult to replicate 😅 Maybe the issue is with a different PHP version or a different OS, which behaves slightly differently or has a different REGEX behaviour...

Here's the latest (v1.2.1) log viewer that handles this test.log file with just a single line, just fine:
<img width="1715" alt="Screenshot 2022-08-31 at 07 38 00" src="https://user-images.githubusercontent.com/8697942/187594070-98dc2160-3953-4639-9134-2e836a7265e0.png">

I've made a small bugfix to validate the last log entry. Could you please upgrade to the latest (`v1.2.3`) version of the Log Viewer first?

If it still fails, could you please let me know:
- the Log Viewer version you're using (bottom right corner)
- the PHP version
- Laravel version
- the OS you're using

This might help me debug the issue if I can mimick the exact environment.

### 2. Failure when no log files are found
I was testing this and found that the exception only occurs when the file from the query param (e.g. `localhost/log-viewer?file=test.log`) is not found. I've added a check for that in the newest `v1.2.3` release

_Originally posted by @arukompas in https://github.com/opcodesio/log-viewer/issues/39#issuecomment-1232465838_

**Comment by arukompas** [comment]
Duplicate, closing
