### ISSUE TITLE
> Hey @dkmonaghan , thanks for reporting this!

### ISSUE THREAD

**Issue by Ashcjs** [opcodesio/log-viewer#74]
> Hey @dkmonaghan , thanks for reporting this!
> 
> The line this fails at means it's not finding the timestamp for this particular log entry. This tells me there might be something in the second log file (the one you're switching to later) that's not properly understood by the log viewer.
> 
> Could you please share the full log file (as an attachment, not a quote here) that you're switching to in your example?
> 
> Thanks! 🙌

Hi @arukompas  - thanks for the quick reply! 

I've just spent some time removing lines from my test log file to see where it fails, and it seems like there's no line specifically that's causing it to fail. I'm actually even more baffled than I was before, and I think the de-selecting of "NOTICE" was actually a red herring. The behaviour happens regardless of whether or not I have any filtering of event types enabled.

I've created a log file called `test.log` containing only the below, and this fails consistently:

```
[2022-08-30 15:42:54] production.NOTICE: Test

```

I'm pretty stumped by this. I have log files that are multiple megabytes large that render fine, yet the above fails to render. The request that actually returns the HTTP 500 is a call to `livewire/message/log-viewer::log-list`, if that helps. Let me know what more information I can provide - if a video would be helpful, I'm happy to provide that.

If it helps, here is the request payload to that Livewire endpoint.

![image](https://user-images.githubusercontent.com/920215/187528833-6c780fc5-7b3c-4468-a5ec-4c08b8175269.png)

Additionally, while experimenting, I discovered that the viewer fails with a fatal error if no logs at all are found in the directory, rather than failing gracefully. It'd be nice if it didn't do this!

_Originally posted by @dkmonaghan in https://github.com/opcodesio/log-viewer/issues/39#issuecomment-1232088786_

**Comment by arukompas** [comment]
Duplicate, closing
