### ISSUE TITLE
livewire.js not found

### ISSUE THREAD

**Issue by taufiqtab** [opcodesio/log-viewer#8]
Hello, nice package, it works great on localhost and i love it, but i have problem with livewire.js script load on my staging server, it's loading to the root of host, but my app url has some path like this :

_mydomain.com/digital-receipt/_

![image](https://user-images.githubusercontent.com/6167609/185838822-194ba0b3-c94b-4637-a871-7236969ba257.png)

![image](https://user-images.githubusercontent.com/6167609/185838662-3b03d47c-17e7-4cf5-bb00-8af56b15dac9.png)

![image](https://user-images.githubusercontent.com/6167609/185839485-cddc7e5f-4b38-482f-aeec-35cff50a1d15.png)

**Comment by snapey** [comment]
This is an issue with Livewire if you install your project in a sub-folder.  Its not an issue with this package.

**Comment by arukompas** [comment]
Hey @taufiqtab ,

Like @snapey  mentioned, it's a problem with Livewire which is used by the Log Viewer.

Fortunately, there's a solution and you can [read about it here](https://laravel-livewire.com/docs/2.x/installation#configuring-the-asset-base-url).

---

Here are quick steps to fix it for you:

1. Publish the Livewire config:
```shell
php artisan livewire:publish --config
```
2. Set the `asset_url` option in the `config/livewire.php` file to your app's subdomain:
```php
    'asset_url' => '/digital-receipt',
```
