### ISSUE TITLE
Small overflow issue

### ISSUE THREAD

**Issue by mortenscheel** [opcodesio/log-viewer#81]
First of all, thanks for this package. It's way better than any of the alternatives.

I noticed a minor UI issue where the dropdown menu gets clipped:
![image](https://user-images.githubusercontent.com/6514342/188314193-3258c62c-ba8a-4845-a926-eb491d8a30dc.png)

**Comment by arukompas** [comment]
@mortenscheel - hey! Thanks for reporting! 😄 

I have **just** tagged a release where @Advaith3600 has fixed the direction of the dropdown when at the bottom of the page. This will also fix the clipping issue as well!

The fix is waiting for you in `v1.2.9`
