### ISSUE TITLE
Error while using Laravel Octane

### ISSUE THREAD

**Issue by lazerg** [opcodesio/log-viewer#9]
### Reproduction steps:

- https://github.com/laravel/framework `9.24.0`
- https://github.com/laravel/octane `1.3.0` **(SWOOLE)**
- https://github.com/opcodesio/log-viewer `1.0.4`

### Screenshot
![Screen Shot 2022-08-22 at 12 05 04](https://user-images.githubusercontent.com/20501725/185859527-3c3bafe1-b336-4ee3-b233-9284c2c26ea1.png)

**Comment by arukompas** [comment]
Hey @lazerg , this should now be fixed in the latest v1.0.5 release.

Let me know if there's still an issue!
